// =====================================================================
// PERMISSION CONSTANTS — Spectra Health HMIS
// =====================================================================
// All granular permissions used by the RBAC system.
// =====================================================================

export const PERMISSIONS = {
  // Patient
  PATIENT_VIEW: "patient.view",
  PATIENT_CREATE: "patient.create",
  PATIENT_EDIT: "patient.edit",
  PATIENT_MERGE: "patient.merge",
  PATIENT_EXPORT: "patient.export",
  PATIENT_DELETE: "patient.delete",

  // Clinical
  CLINICAL_VIEW: "clinical.view",
  CLINICAL_CREATE: "clinical.create",
  CLINICAL_EDIT: "clinical.edit",
  CLINICAL_SIGN: "clinical.sign",
  CLINICAL_AMEND: "clinical.amend",

  // Encounter
  ENCOUNTER_VIEW: "encounter.view",
  ENCOUNTER_CREATE: "encounter.create",
  ENCOUNTER_EDIT: "encounter.edit",
  ENCOUNTER_CLOSE: "encounter.close",

  // Appointments
  APPOINTMENT_VIEW: "appointment.view",
  APPOINTMENT_CREATE: "appointment.create",
  APPOINTMENT_RESCHEDULE: "appointment.reschedule",
  APPOINTMENT_CANCEL: "appointment.cancel",

  // Triage / Vitals
  TRIAGE_VIEW: "triage.view",
  TRIAGE_RECORD: "triage.record",
  VITALS_RECORD: "vitals.record",

  // Immunizations / Vaccinations
  IMMUNIZATION_VIEW: "immunization.view",
  IMMUNIZATION_RECORD: "immunization.record",
  IMMUNIZATION_MANAGE: "immunization.manage", // catalog, schedule, batches
  IMMUNIZATION_AEFI: "immunization.aefi", // report/review adverse events

  // Diagnoses
  DIAGNOSIS_VIEW: "diagnosis.view",
  DIAGNOSIS_CREATE: "diagnosis.create",
  DIAGNOSIS_EDIT: "diagnosis.edit",
  DIAGNOSIS_CONFIRM: "diagnosis.confirm",
  DIAGNOSIS_AMEND: "diagnosis.amend",
  DIAGNOSIS_CATALOG_MANAGE: "diagnosis.catalog.manage",
  DIAGNOSIS_IMPORT: "diagnosis.import",
  DIAGNOSIS_EXPORT: "diagnosis.export",

  // Lab
  LAB_VIEW: "lab.view",
  LAB_ORDER: "lab.order",
  LAB_COLLECT: "lab.collect",
  LAB_PROCESS: "lab.process",
  LAB_RESULT: "lab.result",
  LAB_VERIFY: "lab.verify",
  LAB_AMEND: "lab.amend",

  // Lab Test Catalog (master configuration)
  LAB_CATALOG_VIEW: "lab_catalog.view",
  LAB_CATALOG_MANAGE: "lab_catalog.manage", // create / edit tests
  LAB_CATALOG_ARCHIVE: "lab_catalog.archive", // retire / archive
  LAB_CATALOG_SPECIMEN_MANAGE: "lab_catalog.specimen.manage",
  LAB_CATALOG_RANGE_MANAGE: "lab_catalog.range.manage",
  LAB_CATALOG_CRITICAL_MANAGE: "lab_catalog.critical.manage",
  LAB_CATALOG_PANEL_MANAGE: "lab_catalog.panel.manage",
  LAB_CATALOG_SERVICE_MAP: "lab_catalog.service.map", // map test ↔ Service
  LAB_CATALOG_NHIS_MANAGE: "lab_catalog.nhis.manage",
  LAB_CATALOG_IMPORT: "lab_catalog.import",
  LAB_CATALOG_BULK_UPDATE: "lab_catalog.bulk_update",

  // Imaging
  IMAGING_VIEW: "imaging.view",
  IMAGING_ORDER: "imaging.order",
  IMAGING_PERFORM: "imaging.perform",
  IMAGING_REPORT: "imaging.report",
  IMAGING_VERIFY: "imaging.verify",

  // Procedures
  PROCEDURE_VIEW: "procedure.view",
  PROCEDURE_PERFORM: "procedure.perform",

  // Pharmacy
  PHARMACY_PRESCRIBE: "pharmacy.prescribe",
  PHARMACY_DISPENSE: "pharmacy.dispense",
  PHARMACY_VIEW: "pharmacy.view",
  PHARMACY_INVENTORY: "pharmacy.inventory",
  MEDICATION_MANAGE: "medication.manage",

  // Ambulance
  AMBULANCE_VIEW: "ambulance.view",
  AMBULANCE_MANAGE: "ambulance.manage",
  AMBULANCE_DISPATCH: "ambulance.dispatch",
  FLEET_MANAGE: "fleet.manage",

  // Admission
  ADMISSION_VIEW: "admission.view",
  ADMISSION_CREATE: "admission.create",
  ADMISSION_TRANSFER: "admission.transfer",
  ADMISSION_DISCHARGE: "admission.discharge",
  // Bed Management
  BED_MANAGE: "bed.manage",
  BED_VIEW: "bed.view",
  BED_CREATE: "bed.create",
  BED_EDIT: "bed.edit",
  BED_RETIRE: "bed.retire",
  BED_ASSIGN: "bed.assign",
  BED_RELEASE: "bed.release",
  BED_RESERVE: "bed.reserve",
  BED_BLOCK: "bed.block",
  BED_CLEANING: "bed.cleaning",
  BED_MAINTENANCE: "bed.maintenance",
  BED_TRANSFER: "bed.transfer",
  BED_VIEW_HISTORY: "bed.view_history",

  // Admissions — extended workflow
  ADMISSION_REQUEST: "admission.request", // create admission requests
  ADMISSION_APPROVE: "admission.approve", // approve/decline admission requests
  ADMISSION_BED_ASSIGN: "admission.bed_assign", // assign beds to admissions
  ADMISSION_CONFIRM: "admission.confirm", // confirm patient arrival / check-in
  ADMISSION_PROGRESS_NOTE: "admission.progress_note", // create doctor progress notes
  ADMISSION_DISCHARGE_PLAN: "admission.discharge_plan", // create/edit discharge plans
  ADMISSION_DISCHARGE_SUMMARY: "admission.discharge_summary", // create/edit discharge summaries
  ADMISSION_CARE_TEAM: "admission.care_team", // assign care team members

  // Billing
  BILLING_VIEW: "billing.view",
  BILLING_CREATE: "billing.create",
  BILLING_DISCOUNT: "billing.discount",
  BILLING_REFUND: "billing.refund",
  BILLING_PAYMENT: "billing.payment",
  BILLING_CANCEL: "billing.cancel",

  // Insurance
  INSURANCE_VIEW: "insurance.view",
  INSURANCE_CLAIM: "insurance.claim",
  INSURANCE_VERIFY: "insurance.verify",

  // NHIA CLAIM-it XML Integration
  NHIA_CLAIM_VIEW: "nhia_claim.view",        // view generation history + dashboard
  NHIA_CLAIM_GENERATE: "nhia_claim.generate", // generate / validate / download XML
  NHIA_CLAIM_CONFIG: "nhia_claim.config",    // configure transport, tags, mappings

  // Upstream NHIS workflow — Encounter Coverage, Eligibility, Attendance, Authorization, Claim Readiness
  ENCOUNTER_COVERAGE_VIEW: "encounter_coverage.view",     // view encounter payer/coverage selection
  ENCOUNTER_COVERAGE_MANAGE: "encounter_coverage.manage", // select / change encounter payer
  ATTENDANCE_VERIFICATION_VIEW: "attendance_verification.view",     // view attendance verification records
  ATTENDANCE_VERIFICATION_CAPTURE: "attendance_verification.capture", // capture CCC/OTAC/biometric codes
  ATTENDANCE_VERIFICATION_VERIFY: "attendance_verification.verify",  // mark verified / failed
  CLAIM_READINESS_VIEW: "claim_readiness.view",           // view readiness assessments
  CLAIM_READINESS_EVALUATE: "claim_readiness.evaluate",   // trigger readiness evaluation

  // Insurance Providers (master configuration)
  INSURANCE_PROVIDER_VIEW: "insurance_provider.view",
  INSURANCE_PROVIDER_MANAGE: "insurance_provider.manage", // create / edit providers
  INSURANCE_PROVIDER_ARCHIVE: "insurance_provider.archive", // retire / archive
  INSURANCE_PLAN_MANAGE: "insurance_plan.manage", // create / edit plans
  INSURANCE_COVERAGE_MANAGE: "insurance_coverage.manage", // coverage rules
  INSURANCE_ELIGIBILITY_MANAGE: "insurance_eligibility.manage", // verify eligibility
  INSURANCE_AUTHORIZATION_MANAGE: "insurance_authorization.manage", // pre-authorizations
  INSURANCE_PROVIDER_IMPORT: "insurance_provider.import",

  // Inventory
  INVENTORY_VIEW: "inventory.view",
  INVENTORY_RECEIVE: "inventory.receive",
  INVENTORY_ISSUE: "inventory.issue",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  PROCUREMENT_MANAGE: "procurement.manage",

  // Reports
  REPORT_VIEW: "report.view",
  REPORT_EXPORT: "report.export",
  ANALYTICS_VIEW: "analytics.view",

  // Users / Roles / Permissions
  USER_CREATE: "user.create",
  USER_EDIT: "user.edit",
  USER_DISABLE: "user.disable",
  USER_VIEW: "user.view",
  ROLE_CREATE: "role.create",
  ROLE_EDIT: "role.edit",
  ROLE_VIEW: "role.view",
  PERMISSION_ASSIGN: "permission.assign",

  // Facility / Department
  FACILITY_MANAGE: "facility.manage",
  DEPARTMENT_MANAGE: "department.manage",

  // Staff
  STAFF_VIEW: "staff.view",
  STAFF_MANAGE: "staff.manage",
  SHIFT_MANAGE: "shift.manage",

  // Shifts & Leave — advanced workforce scheduling
  SHIFT_VIEW: "shift.view",
  SHIFT_CREATE: "shift.create",
  SHIFT_EDIT: "shift.edit",
  SHIFT_DELETE: "shift.delete",
  ROSTER_MANAGE: "roster.manage",
  ROSTER_PUBLISH: "roster.publish",
  ROSTER_LOCK: "roster.lock",
  SHIFT_ASSIGN: "shift.assign",
  ON_CALL_MANAGE: "on_call.manage",
  SHIFT_SWAP_REQUEST: "shift_swap.request",
  SHIFT_SWAP_APPROVE: "shift_swap.approve",
  LEAVE_REQUEST: "leave.request",
  LEAVE_VIEW: "leave.view",
  LEAVE_APPROVE: "leave.approve",
  LEAVE_MANAGE: "leave.manage",
  LEAVE_BALANCE_MANAGE: "leave_balance.manage",
  LEAVE_POLICY_MANAGE: "leave_policy.manage",
  HOLIDAY_MANAGE: "holiday.manage",
  STAFFING_REQUIREMENT_MANAGE: "staffing_requirement.manage",
  WORKFORCE_REPORT_VIEW: "workforce_report.view",
  WORKFORCE_DATA_EXPORT: "workforce_data.export",
  COVERAGE_MANAGE: "coverage.manage",
  STAFF_AVAILABILITY_MANAGE: "staff_availability.manage",

  // Attendance — advanced workforce attendance system
  ATTENDANCE_VIEW: "attendance.view",
  ATTENDANCE_RECORD: "attendance.record",
  ATTENDANCE_EDIT: "attendance.edit",
  ATTENDANCE_MANAGE: "attendance.manage",
  ATTENDANCE_REVIEW: "attendance.review",
  ATTENDANCE_CORRECTION_APPROVE: "attendance_correction.approve",
  ATTENDANCE_POLICY_MANAGE: "attendance_policy.manage",
  ATTENDANCE_REPORT_VIEW: "attendance_report.view",
  ATTENDANCE_EXPORT: "attendance.export",
  OVERTIME_MANAGE: "overtime.manage",
  ATTENDANCE_PERIOD_LOCK: "attendance_period.lock",
  ATTENDANCE_PERIOD_UNLOCK: "attendance_period.unlock",

  // Training & Staff Development
  TRAINING_VIEW: "training.view",
  TRAINING_CREATE: "training.create",
  TRAINING_EDIT: "training.edit",
  TRAINING_DELETE: "training.delete",
  TRAINING_MANAGE: "training.manage",
  TRAINING_ENROLL: "training.enroll",
  TRAINING_APPROVE: "training.approve",
  TRAINING_ATTENDANCE_RECORD: "training_attendance.record",
  TRAINING_ASSESSMENT_MANAGE: "training_assessment.manage",
  TRAINING_CERTIFICATE_MANAGE: "training_certificate.manage",
  TRAINING_COMPETENCY_MANAGE: "training_competency.manage",
  TRAINING_CPD_MANAGE: "training_cpd.manage",
  TRAINING_REQUIREMENT_MANAGE: "training_requirement.manage",
  TRAINING_REPORT_VIEW: "training_report.view",
  TRAINING_REPORT_EXPORT: "training_report.export",
  TRAINING_BUDGET_MANAGE: "training_budget.manage",

  // Certifications & Credentials
  CERTIFICATION_VIEW: "certification.view",
  CERTIFICATION_CREATE: "certification.create",
  CERTIFICATION_EDIT: "certification.edit",
  CERTIFICATION_DELETE: "certification.delete",
  CERTIFICATION_VERIFY: "certification.verify",
  CERTIFICATION_APPROVE: "certification.approve",
  CERTIFICATION_RENEW: "certification.renew",
  CERTIFICATION_SUSPEND: "certification.suspend",
  CERTIFICATION_REVOKE: "certification.revoke",
  CERTIFICATION_REQUIREMENT_MANAGE: "certification_requirement.manage",
  CERTIFICATION_ISSUER_MANAGE: "certification_issuer.manage",
  CERTIFICATION_DOCUMENT_VIEW: "certification_document.view",
  CERTIFICATION_REPORT_EXPORT: "certification_report.export",

  // Finance & Payroll
  FINANCE_VIEW: "finance.view",
  FINANCE_MANAGE: "finance.manage",
  PAYROLL_VIEW: "payroll.view",
  PAYROLL_CREATE: "payroll.create",
  PAYROLL_PROCESS: "payroll.process",
  PAYROLL_REVIEW: "payroll.review",
  PAYROLL_APPROVE: "payroll.approve",
  PAYROLL_LOCK: "payroll.lock",
  COMPENSATION_MANAGE: "compensation.manage",
  ALLOWANCE_MANAGE: "allowance.manage",
  DEDUCTION_MANAGE: "deduction.manage",
  OVERTIME_PAYROLL_MANAGE: "overtime_payroll.manage",
  LOAN_MANAGE: "loan.manage",
  ADVANCE_MANAGE: "advance.manage",
  PAYSLIP_VIEW: "payslip.view",
  PAYSLIP_VIEW_OWN: "payslip.view_own",
  FINANCE_REPORT_VIEW: "finance_report.view",
  FINANCE_REPORT_EXPORT: "finance_report.export",
  STATUTORY_RULE_MANAGE: "statutory_rule.manage",

  // Nursing Documentation
  NURSING_VIEW: "nursing.view",
  NURSING_NOTE_CREATE: "nursing.note.create",
  NURSING_NOTE_SIGN: "nursing.note.sign",
  NURSING_NOTE_AMEND: "nursing.note.amend",
  NURSING_CARE_PLAN_MANAGE: "nursing.care_plan.manage",
  NURSING_TASK_MANAGE: "nursing.task.manage",
  NURSING_HANDOVER: "nursing.handover",
  NURSING_ESCALATE: "nursing.escalate",
  NURSING_WOUND_CARE: "nursing.wound_care",
  NURSING_RISK_ASSESSMENT: "nursing.risk_assessment",
  NURSING_INTERVENTION: "nursing.intervention",
  NURSING_REPORTS: "nursing.reports",

  // Ward Rounds
  WARD_ROUND_VIEW: "ward_round.view",
  WARD_ROUND_CREATE: "ward_round.create",
  WARD_ROUND_SCHEDULE: "ward_round.schedule",
  WARD_ROUND_START: "ward_round.start",
  WARD_ROUND_DOCUMENT: "ward_round.document",
  WARD_ROUND_SIGN: "ward_round.sign",
  WARD_ROUND_AMEND: "ward_round.amend",
  WARD_ROUND_COMPLETE: "ward_round.complete",
  WARD_ROUND_ACTION_MANAGE: "ward_round.action.manage",
  WARD_ROUND_REPORTS: "ward_round.reports",

  // Audit / Security
  AUDIT_VIEW: "audit.view",
  AUDIT_EXPORT: "audit.export",
  BREAK_GLASS: "break_glass.use",
  SECURITY_DASHBOARD: "security.dashboard",
  DATA_EXPORT: "data.export",

  // System Settings
  SETTINGS_MANAGE: "settings.manage",
  SETTINGS_VIEW: "settings.view",

  // Notifications / Tasks
  TASK_ASSIGN: "task.assign",
  TASK_COMPLETE: "task.complete",

  // Documents
  DOCUMENT_UPLOAD: "document.upload",
  DOCUMENT_VIEW: "document.view",
  DOCUMENT_DELETE: "document.delete",

  // Maternity
  MATERNITY_VIEW: "maternity.view",
  MATERNITY_MANAGE: "maternity.manage",
  MATERNITY_ANC_RECORD: "maternity.anc.record",
  MATERNITY_DELIVERY_RECORD: "maternity.delivery.record",
  MATERNITY_NEWBORN_RECORD: "maternity.newborn.record",

  // Mortuary
  MORTUARY_VIEW: "mortuary.view",
  MORTUARY_MANAGE: "mortuary.manage",

  // Blood Bank
  BLOODBANK_VIEW: "bloodbank.view",
  BLOODBANK_MANAGE: "bloodbank.manage",
  BLOODBANK_TRANSFUSE: "bloodbank.transfuse",

  // Operating Theatre
  THEATRE_VIEW: "theatre.view",
  THEATRE_MANAGE: "theatre.manage",
  THEATRE_PERFORM: "theatre.perform",

  // Critical Care (ICU/NICU)
  CRITICAL_CARE_VIEW: "critical_care.view",
  CRITICAL_CARE_MANAGE: "critical_care.manage",

  // Specialty Clinics (Dental/Eye/ENT/etc.)
  SPECIALTY_VIEW: "specialty.view",
  SPECIALTY_MANAGE: "specialty.manage",
  SPECIALTY_APPOINTMENTS: "specialty.appointments",
  SPECIALTY_REFERRALS: "specialty.referrals",

  // Support Services (Laundry/Housekeeping/Catering/Waste/Security/Transport)
  SUPPORT_SERVICES_VIEW: "support_services.view",
  SUPPORT_SERVICES_MANAGE: "support_services.manage",

  // Patient Relations
  PATIENT_RELATIONS_VIEW: "patient_relations.view",
  PATIENT_RELATIONS_MANAGE: "patient_relations.manage",

  // Quality Assurance
  QA_VIEW: "qa.view",
  QA_MANAGE: "qa.manage",

  // Risk Management
  RISK_VIEW: "risk.view",
  RISK_MANAGE: "risk.manage",

  // Legal / Compliance
  LEGAL_VIEW: "legal.view",
  LEGAL_MANAGE: "legal.manage",

  // Research
  RESEARCH_VIEW: "research.view",
  RESEARCH_MANAGE: "research.manage",

  // Public Relations
  PR_VIEW: "pr.view",
  PR_MANAGE: "pr.manage",

  // IT Operations
  IT_VIEW: "it.view",
  IT_MANAGE: "it.manage",

  // Coding & Claims
  CODING_VIEW: "coding.view",
  CODING_MANAGE: "coding.manage",

  // Community Health
  COMMUNITY_HEALTH_VIEW: "community_health.view",
  COMMUNITY_HEALTH_MANAGE: "community_health.manage",

  // Home Care
  HOME_CARE_VIEW: "home_care.view",
  HOME_CARE_MANAGE: "home_care.manage",

  // Histopathology
  HISTOPATHOLOGY_VIEW: "histopathology.view",
  HISTOPATHOLOGY_MANAGE: "histopathology.manage",

  // Recovery Room
  RECOVERY_VIEW: "recovery.view",
  RECOVERY_MANAGE: "recovery.manage",

  // Internal Audit (extends existing AUDIT_VIEW)
  AUDIT_MANAGE: "audit.manage",
} as const;

export type PermissionCode = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

// =====================================================================
// ROLE -> PERMISSION MAPPING (default system roles)
// =====================================================================

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

const CLINICAL_FULL = [
  PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_EDIT,
  PERMISSIONS.CLINICAL_VIEW, PERMISSIONS.CLINICAL_CREATE, PERMISSIONS.CLINICAL_EDIT,
  PERMISSIONS.ENCOUNTER_VIEW, PERMISSIONS.ENCOUNTER_CREATE, PERMISSIONS.ENCOUNTER_EDIT, PERMISSIONS.ENCOUNTER_CLOSE,
  PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_RESCHEDULE, PERMISSIONS.APPOINTMENT_CANCEL,
  PERMISSIONS.TRIAGE_VIEW,
  PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE,
  PERMISSIONS.DIAGNOSIS_EDIT, PERMISSIONS.DIAGNOSIS_CONFIRM, PERMISSIONS.DIAGNOSIS_AMEND,
  PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_ORDER,
  PERMISSIONS.IMAGING_VIEW, PERMISSIONS.IMAGING_ORDER,
  PERMISSIONS.PROCEDURE_VIEW,
  PERMISSIONS.PHARMACY_VIEW, PERMISSIONS.PHARMACY_PRESCRIBE,
  PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.BILLING_VIEW,
  PERMISSIONS.REPORT_VIEW,
  PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_UPLOAD,
  PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
];

// CLINICAL_VIEW_ONLY — for nurses and other clinical support staff who can VIEW
// clinical data and create nursing notes/triage, but CANNOT create consultations
// or sign clinical notes (only doctors/specialists/medical officers can).
const CLINICAL_VIEW_ONLY = CLINICAL_FULL.filter(
  (p) => p !== PERMISSIONS.CLINICAL_CREATE
);

export const ROLE_PERMISSIONS: Record<string, PermissionCode[]> = {
  super_admin: ALL_PERMISSIONS,

  organization_admin: [
    ...CLINICAL_FULL,
    PERMISSIONS.PATIENT_MERGE, PERMISSIONS.PATIENT_EXPORT, PERMISSIONS.PATIENT_DELETE,
    PERMISSIONS.CLINICAL_SIGN, PERMISSIONS.CLINICAL_AMEND,
    PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.IMMUNIZATION_VIEW, PERMISSIONS.IMMUNIZATION_RECORD, PERMISSIONS.IMMUNIZATION_MANAGE, PERMISSIONS.IMMUNIZATION_AEFI,
    PERMISSIONS.LAB_COLLECT, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RESULT, PERMISSIONS.LAB_VERIFY, PERMISSIONS.LAB_AMEND,
    PERMISSIONS.LAB_CATALOG_VIEW, PERMISSIONS.LAB_CATALOG_MANAGE, PERMISSIONS.LAB_CATALOG_ARCHIVE,
    PERMISSIONS.LAB_CATALOG_SPECIMEN_MANAGE, PERMISSIONS.LAB_CATALOG_RANGE_MANAGE, PERMISSIONS.LAB_CATALOG_CRITICAL_MANAGE,
    PERMISSIONS.LAB_CATALOG_PANEL_MANAGE, PERMISSIONS.LAB_CATALOG_SERVICE_MAP, PERMISSIONS.LAB_CATALOG_NHIS_MANAGE,
    PERMISSIONS.LAB_CATALOG_IMPORT, PERMISSIONS.LAB_CATALOG_BULK_UPDATE,
    PERMISSIONS.IMAGING_PERFORM, PERMISSIONS.IMAGING_REPORT, PERMISSIONS.IMAGING_VERIFY,
    PERMISSIONS.PROCEDURE_PERFORM,
    PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_INVENTORY,
    PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_TRANSFER, PERMISSIONS.ADMISSION_DISCHARGE, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_CREATE, PERMISSIONS.BED_EDIT, PERMISSIONS.BED_RETIRE,
    PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_RELEASE, PERMISSIONS.BED_RESERVE,
    PERMISSIONS.BED_BLOCK, PERMISSIONS.BED_CLEANING, PERMISSIONS.BED_MAINTENANCE,
    PERMISSIONS.BED_TRANSFER, PERMISSIONS.BED_VIEW_HISTORY,
    PERMISSIONS.ADMISSION_REQUEST, PERMISSIONS.ADMISSION_APPROVE, PERMISSIONS.ADMISSION_BED_ASSIGN,
    PERMISSIONS.ADMISSION_CONFIRM, PERMISSIONS.ADMISSION_PROGRESS_NOTE,
    PERMISSIONS.ADMISSION_DISCHARGE_PLAN, PERMISSIONS.ADMISSION_DISCHARGE_SUMMARY,
    PERMISSIONS.ADMISSION_CARE_TEAM,
    PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_DISCOUNT, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_CANCEL,
    PERMISSIONS.INSURANCE_VIEW, PERMISSIONS.INSURANCE_CLAIM, PERMISSIONS.INSURANCE_VERIFY,
    PERMISSIONS.INSURANCE_PROVIDER_VIEW, PERMISSIONS.INSURANCE_PROVIDER_MANAGE, PERMISSIONS.INSURANCE_PROVIDER_ARCHIVE,
    PERMISSIONS.INSURANCE_PLAN_MANAGE, PERMISSIONS.INSURANCE_COVERAGE_MANAGE,
    PERMISSIONS.INSURANCE_ELIGIBILITY_MANAGE, PERMISSIONS.INSURANCE_AUTHORIZATION_MANAGE,
    PERMISSIONS.INSURANCE_PROVIDER_IMPORT,
    // NHIA CLAIM-it XML integration (full access for org admin)
    PERMISSIONS.NHIA_CLAIM_VIEW, PERMISSIONS.NHIA_CLAIM_GENERATE, PERMISSIONS.NHIA_CLAIM_CONFIG,
    // Upstream NHIS workflow (full access for org admin)
    PERMISSIONS.ENCOUNTER_COVERAGE_VIEW, PERMISSIONS.ENCOUNTER_COVERAGE_MANAGE,
    PERMISSIONS.ATTENDANCE_VERIFICATION_VIEW, PERMISSIONS.ATTENDANCE_VERIFICATION_CAPTURE, PERMISSIONS.ATTENDANCE_VERIFICATION_VERIFY,
    PERMISSIONS.CLAIM_READINESS_VIEW, PERMISSIONS.CLAIM_READINESS_EVALUATE,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_RECEIVE, PERMISSIONS.INVENTORY_ISSUE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.REPORT_EXPORT, PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.USER_CREATE, PERMISSIONS.USER_EDIT, PERMISSIONS.USER_DISABLE, PERMISSIONS.USER_VIEW,
    PERMISSIONS.ROLE_CREATE, PERMISSIONS.ROLE_EDIT, PERMISSIONS.ROLE_VIEW, PERMISSIONS.PERMISSION_ASSIGN,
    PERMISSIONS.FACILITY_MANAGE, PERMISSIONS.DEPARTMENT_MANAGE,
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE, PERMISSIONS.SHIFT_MANAGE,
    // Payroll permissions (org admin)
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_CREATE, PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_REVIEW, PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.COMPENSATION_MANAGE, PERMISSIONS.ALLOWANCE_MANAGE, PERMISSIONS.DEDUCTION_MANAGE,
    PERMISSIONS.LOAN_MANAGE, PERMISSIONS.ADVANCE_MANAGE, PERMISSIONS.PAYSLIP_VIEW,
    PERMISSIONS.STATUTORY_RULE_MANAGE, PERMISSIONS.OVERTIME_PAYROLL_MANAGE,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.FINANCE_REPORT_VIEW, PERMISSIONS.FINANCE_REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW, PERMISSIONS.AUDIT_EXPORT, PERMISSIONS.SECURITY_DASHBOARD, PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.SETTINGS_MANAGE, PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.DIAGNOSIS_CATALOG_MANAGE, PERMISSIONS.DIAGNOSIS_IMPORT, PERMISSIONS.DIAGNOSIS_EXPORT,
    PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE, PERMISSIONS.DIAGNOSIS_EDIT, PERMISSIONS.DIAGNOSIS_CONFIRM, PERMISSIONS.DIAGNOSIS_AMEND,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_MANAGE,
    PERMISSIONS.MATERNITY_ANC_RECORD, PERMISSIONS.MATERNITY_DELIVERY_RECORD, PERMISSIONS.MATERNITY_NEWBORN_RECORD,
    PERMISSIONS.BREAK_GLASS,
    // Extended module permissions (org admin)
    PERMISSIONS.MORTUARY_VIEW, PERMISSIONS.MORTUARY_MANAGE,
    PERMISSIONS.BLOODBANK_VIEW, PERMISSIONS.BLOODBANK_MANAGE, PERMISSIONS.BLOODBANK_TRANSFUSE,
    PERMISSIONS.THEATRE_VIEW, PERMISSIONS.THEATRE_MANAGE, PERMISSIONS.THEATRE_PERFORM,
    PERMISSIONS.CRITICAL_CARE_VIEW, PERMISSIONS.CRITICAL_CARE_MANAGE,
    PERMISSIONS.SPECIALTY_VIEW, PERMISSIONS.SPECIALTY_MANAGE,
    PERMISSIONS.SPECIALTY_APPOINTMENTS, PERMISSIONS.SPECIALTY_REFERRALS,
    PERMISSIONS.SUPPORT_SERVICES_VIEW, PERMISSIONS.SUPPORT_SERVICES_MANAGE,
    PERMISSIONS.PATIENT_RELATIONS_VIEW, PERMISSIONS.PATIENT_RELATIONS_MANAGE,
    PERMISSIONS.QA_VIEW, PERMISSIONS.QA_MANAGE,
    PERMISSIONS.RISK_VIEW, PERMISSIONS.RISK_MANAGE,
    PERMISSIONS.LEGAL_VIEW, PERMISSIONS.LEGAL_MANAGE,
    PERMISSIONS.RESEARCH_VIEW, PERMISSIONS.RESEARCH_MANAGE,
    PERMISSIONS.PR_VIEW, PERMISSIONS.PR_MANAGE,
    PERMISSIONS.IT_VIEW, PERMISSIONS.IT_MANAGE,
    PERMISSIONS.CODING_VIEW, PERMISSIONS.CODING_MANAGE,
    PERMISSIONS.COMMUNITY_HEALTH_VIEW, PERMISSIONS.COMMUNITY_HEALTH_MANAGE,
    PERMISSIONS.HOME_CARE_VIEW, PERMISSIONS.HOME_CARE_MANAGE,
    PERMISSIONS.HISTOPATHOLOGY_VIEW, PERMISSIONS.HISTOPATHOLOGY_MANAGE,
    PERMISSIONS.RECOVERY_VIEW, PERMISSIONS.RECOVERY_MANAGE,
    PERMISSIONS.AUDIT_MANAGE,
  ],

  facility_admin: [
    ...CLINICAL_FULL,
    PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.IMMUNIZATION_VIEW, PERMISSIONS.IMMUNIZATION_RECORD, PERMISSIONS.IMMUNIZATION_MANAGE, PERMISSIONS.IMMUNIZATION_AEFI,
    PERMISSIONS.AMBULANCE_VIEW, PERMISSIONS.AMBULANCE_DISPATCH,
    PERMISSIONS.LAB_COLLECT, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RESULT, PERMISSIONS.LAB_VERIFY,
    PERMISSIONS.LAB_CATALOG_VIEW, PERMISSIONS.LAB_CATALOG_MANAGE, PERMISSIONS.LAB_CATALOG_ARCHIVE,
    PERMISSIONS.LAB_CATALOG_SPECIMEN_MANAGE, PERMISSIONS.LAB_CATALOG_RANGE_MANAGE, PERMISSIONS.LAB_CATALOG_CRITICAL_MANAGE,
    PERMISSIONS.LAB_CATALOG_PANEL_MANAGE, PERMISSIONS.LAB_CATALOG_SERVICE_MAP, PERMISSIONS.LAB_CATALOG_NHIS_MANAGE,
    PERMISSIONS.LAB_CATALOG_IMPORT, PERMISSIONS.LAB_CATALOG_BULK_UPDATE,
    PERMISSIONS.IMAGING_PERFORM, PERMISSIONS.IMAGING_REPORT,
    PERMISSIONS.PROCEDURE_PERFORM,
    PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_INVENTORY,
    PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_TRANSFER, PERMISSIONS.ADMISSION_DISCHARGE, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_CREATE, PERMISSIONS.BED_EDIT, PERMISSIONS.BED_RETIRE,
    PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_RELEASE, PERMISSIONS.BED_RESERVE,
    PERMISSIONS.BED_BLOCK, PERMISSIONS.BED_CLEANING, PERMISSIONS.BED_MAINTENANCE,
    PERMISSIONS.BED_TRANSFER, PERMISSIONS.BED_VIEW_HISTORY,
    PERMISSIONS.ADMISSION_REQUEST, PERMISSIONS.ADMISSION_APPROVE, PERMISSIONS.ADMISSION_BED_ASSIGN,
    PERMISSIONS.ADMISSION_CONFIRM, PERMISSIONS.ADMISSION_PROGRESS_NOTE,
    PERMISSIONS.ADMISSION_DISCHARGE_PLAN, PERMISSIONS.ADMISSION_DISCHARGE_SUMMARY,
    PERMISSIONS.ADMISSION_CARE_TEAM,
    PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_DISCOUNT,
    // NHIA CLAIM-it — facility admin can view + generate XML
    PERMISSIONS.NHIA_CLAIM_VIEW, PERMISSIONS.NHIA_CLAIM_GENERATE,
    // Upstream NHIS workflow — facility admin can manage coverage, capture attendance, evaluate readiness
    PERMISSIONS.ENCOUNTER_COVERAGE_VIEW, PERMISSIONS.ENCOUNTER_COVERAGE_MANAGE,
    PERMISSIONS.ATTENDANCE_VERIFICATION_VIEW, PERMISSIONS.ATTENDANCE_VERIFICATION_CAPTURE, PERMISSIONS.ATTENDANCE_VERIFICATION_VERIFY,
    PERMISSIONS.CLAIM_READINESS_VIEW, PERMISSIONS.CLAIM_READINESS_EVALUATE,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_RECEIVE, PERMISSIONS.INVENTORY_ISSUE,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.USER_VIEW, PERMISSIONS.USER_CREATE, PERMISSIONS.USER_EDIT,
    PERMISSIONS.STAFF_VIEW, PERMISSIONS.STAFF_MANAGE, PERMISSIONS.SHIFT_MANAGE,
    // Payroll permissions (org admin)
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_CREATE, PERMISSIONS.PAYROLL_PROCESS,
    PERMISSIONS.PAYROLL_REVIEW, PERMISSIONS.PAYROLL_APPROVE, PERMISSIONS.PAYROLL_LOCK,
    PERMISSIONS.COMPENSATION_MANAGE, PERMISSIONS.ALLOWANCE_MANAGE, PERMISSIONS.DEDUCTION_MANAGE,
    PERMISSIONS.LOAN_MANAGE, PERMISSIONS.ADVANCE_MANAGE, PERMISSIONS.PAYSLIP_VIEW,
    PERMISSIONS.STATUTORY_RULE_MANAGE, PERMISSIONS.OVERTIME_PAYROLL_MANAGE,
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.FINANCE_REPORT_VIEW, PERMISSIONS.FINANCE_REPORT_EXPORT,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.DIAGNOSIS_VIEW, PERMISSIONS.DIAGNOSIS_CREATE, PERMISSIONS.DIAGNOSIS_EDIT, PERMISSIONS.DIAGNOSIS_CONFIRM, PERMISSIONS.DIAGNOSIS_AMEND,
    PERMISSIONS.DIAGNOSIS_CATALOG_MANAGE, PERMISSIONS.DIAGNOSIS_EXPORT,
    PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_MANAGE,
    PERMISSIONS.MATERNITY_ANC_RECORD, PERMISSIONS.MATERNITY_DELIVERY_RECORD, PERMISSIONS.MATERNITY_NEWBORN_RECORD,
    PERMISSIONS.BREAK_GLASS,
    // Facility admin extended modules
    PERMISSIONS.MORTUARY_VIEW, PERMISSIONS.MORTUARY_MANAGE,
    PERMISSIONS.BLOODBANK_VIEW, PERMISSIONS.BLOODBANK_MANAGE,
    PERMISSIONS.THEATRE_VIEW, PERMISSIONS.THEATRE_MANAGE, PERMISSIONS.THEATRE_PERFORM,
    PERMISSIONS.CRITICAL_CARE_VIEW, PERMISSIONS.CRITICAL_CARE_MANAGE,
    PERMISSIONS.SPECIALTY_VIEW, PERMISSIONS.SPECIALTY_MANAGE,
    PERMISSIONS.SPECIALTY_APPOINTMENTS, PERMISSIONS.SPECIALTY_REFERRALS,
    PERMISSIONS.SUPPORT_SERVICES_VIEW, PERMISSIONS.SUPPORT_SERVICES_MANAGE,
    PERMISSIONS.PATIENT_RELATIONS_VIEW, PERMISSIONS.PATIENT_RELATIONS_MANAGE,
    PERMISSIONS.QA_VIEW,
    PERMISSIONS.RISK_VIEW,
    PERMISSIONS.LEGAL_VIEW,
    PERMISSIONS.RESEARCH_VIEW,
    PERMISSIONS.PR_VIEW,
    PERMISSIONS.IT_VIEW, PERMISSIONS.IT_MANAGE,
    PERMISSIONS.CODING_VIEW, PERMISSIONS.CODING_MANAGE,
    PERMISSIONS.COMMUNITY_HEALTH_VIEW, PERMISSIONS.COMMUNITY_HEALTH_MANAGE,
    PERMISSIONS.HOME_CARE_VIEW, PERMISSIONS.HOME_CARE_MANAGE,
    PERMISSIONS.HISTOPATHOLOGY_VIEW,
    PERMISSIONS.RECOVERY_VIEW, PERMISSIONS.RECOVERY_MANAGE,
  ],

  doctor: [
    ...CLINICAL_FULL,
    PERMISSIONS.CLINICAL_SIGN, PERMISSIONS.CLINICAL_AMEND,
    PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.IMMUNIZATION_VIEW, PERMISSIONS.IMMUNIZATION_RECORD, PERMISSIONS.IMMUNIZATION_AEFI,
    PERMISSIONS.AMBULANCE_VIEW, PERMISSIONS.AMBULANCE_DISPATCH,
    PERMISSIONS.PROCEDURE_PERFORM,
    PERMISSIONS.NURSING_VIEW,
    // Ward Rounds
    PERMISSIONS.WARD_ROUND_VIEW, PERMISSIONS.WARD_ROUND_CREATE, PERMISSIONS.WARD_ROUND_SCHEDULE,
    PERMISSIONS.WARD_ROUND_START, PERMISSIONS.WARD_ROUND_DOCUMENT, PERMISSIONS.WARD_ROUND_SIGN,
    PERMISSIONS.WARD_ROUND_AMEND, PERMISSIONS.WARD_ROUND_COMPLETE, PERMISSIONS.WARD_ROUND_ACTION_MANAGE,
    PERMISSIONS.ADMISSION_CREATE, PERMISSIONS.ADMISSION_TRANSFER, PERMISSIONS.ADMISSION_DISCHARGE, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_RELEASE, PERMISSIONS.BED_TRANSFER, PERMISSIONS.BED_VIEW_HISTORY,
    PERMISSIONS.ADMISSION_REQUEST, PERMISSIONS.ADMISSION_BED_ASSIGN,
    PERMISSIONS.ADMISSION_PROGRESS_NOTE, PERMISSIONS.ADMISSION_DISCHARGE_PLAN,
    PERMISSIONS.ADMISSION_DISCHARGE_SUMMARY, PERMISSIONS.ADMISSION_CARE_TEAM,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_MANAGE,
    PERMISSIONS.MATERNITY_ANC_RECORD, PERMISSIONS.MATERNITY_DELIVERY_RECORD, PERMISSIONS.MATERNITY_NEWBORN_RECORD,
    PERMISSIONS.BREAK_GLASS,
    // Doctor extended modules
    PERMISSIONS.THEATRE_VIEW, PERMISSIONS.THEATRE_PERFORM,
    PERMISSIONS.CRITICAL_CARE_VIEW,
    PERMISSIONS.SPECIALTY_VIEW, PERMISSIONS.SPECIALTY_MANAGE,
    PERMISSIONS.SPECIALTY_APPOINTMENTS, PERMISSIONS.SPECIALTY_REFERRALS,
    PERMISSIONS.BLOODBANK_VIEW, PERMISSIONS.BLOODBANK_TRANSFUSE,
    PERMISSIONS.HISTOPATHOLOGY_VIEW,
    PERMISSIONS.RECOVERY_VIEW,
    PERMISSIONS.HOME_CARE_VIEW,
    PERMISSIONS.PATIENT_RELATIONS_VIEW,
  ],

  nurse: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW, PERMISSIONS.CLINICAL_EDIT,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.TRIAGE_VIEW, PERMISSIONS.TRIAGE_RECORD, PERMISSIONS.VITALS_RECORD,
    PERMISSIONS.IMMUNIZATION_VIEW, PERMISSIONS.IMMUNIZATION_RECORD,
    PERMISSIONS.MATERNITY_VIEW, PERMISSIONS.MATERNITY_ANC_RECORD, PERMISSIONS.MATERNITY_DELIVERY_RECORD, PERMISSIONS.MATERNITY_NEWBORN_RECORD,
    PERMISSIONS.AMBULANCE_VIEW, PERMISSIONS.AMBULANCE_DISPATCH,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_COLLECT,
    PERMISSIONS.PHARMACY_VIEW,
    // Nursing documentation
    PERMISSIONS.NURSING_VIEW, PERMISSIONS.NURSING_NOTE_CREATE, PERMISSIONS.NURSING_NOTE_SIGN,
    PERMISSIONS.NURSING_NOTE_AMEND, PERMISSIONS.NURSING_CARE_PLAN_MANAGE,
    PERMISSIONS.NURSING_TASK_MANAGE, PERMISSIONS.NURSING_HANDOVER,
    PERMISSIONS.NURSING_ESCALATE, PERMISSIONS.NURSING_WOUND_CARE,
    PERMISSIONS.NURSING_RISK_ASSESSMENT, PERMISSIONS.NURSING_INTERVENTION,
    PERMISSIONS.NURSING_REPORTS,
    // Ward Rounds
    PERMISSIONS.WARD_ROUND_VIEW, PERMISSIONS.WARD_ROUND_CREATE, PERMISSIONS.WARD_ROUND_SCHEDULE,
    PERMISSIONS.WARD_ROUND_START, PERMISSIONS.WARD_ROUND_DOCUMENT, PERMISSIONS.WARD_ROUND_SIGN,
    PERMISSIONS.WARD_ROUND_AMEND, PERMISSIONS.WARD_ROUND_COMPLETE, PERMISSIONS.WARD_ROUND_ACTION_MANAGE,
    PERMISSIONS.WARD_ROUND_REPORTS,
    PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.BED_MANAGE,
    PERMISSIONS.BED_VIEW, PERMISSIONS.BED_ASSIGN, PERMISSIONS.BED_RELEASE, PERMISSIONS.BED_CLEANING, PERMISSIONS.BED_VIEW_HISTORY,
    PERMISSIONS.ADMISSION_CONFIRM, PERMISSIONS.ADMISSION_PROGRESS_NOTE,
    PERMISSIONS.PROCEDURE_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
    // Nurse extended modules
    PERMISSIONS.MORTUARY_VIEW,
    PERMISSIONS.BLOODBANK_VIEW,
    PERMISSIONS.THEATRE_VIEW,
    PERMISSIONS.CRITICAL_CARE_VIEW, PERMISSIONS.CRITICAL_CARE_MANAGE,
    PERMISSIONS.SPECIALTY_VIEW,
    PERMISSIONS.SPECIALTY_APPOINTMENTS,
    PERMISSIONS.SUPPORT_SERVICES_VIEW,
    PERMISSIONS.PATIENT_RELATIONS_VIEW,
    PERMISSIONS.RECOVERY_VIEW, PERMISSIONS.RECOVERY_MANAGE,
    PERMISSIONS.HOME_CARE_VIEW, PERMISSIONS.HOME_CARE_MANAGE,
  ],

  pharmacist: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.PHARMACY_VIEW, PERMISSIONS.PHARMACY_DISPENSE, PERMISSIONS.PHARMACY_INVENTORY,
    PERMISSIONS.MEDICATION_MANAGE,
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_ISSUE, PERMISSIONS.INVENTORY_ADJUST,
    PERMISSIONS.IMMUNIZATION_VIEW, PERMISSIONS.IMMUNIZATION_MANAGE,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  laboratory_scientist: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.LAB_VIEW, PERMISSIONS.LAB_COLLECT, PERMISSIONS.LAB_PROCESS, PERMISSIONS.LAB_RESULT, PERMISSIONS.LAB_VERIFY, PERMISSIONS.LAB_AMEND,
    // Lab Test Catalog — scientists manage catalog configuration
    PERMISSIONS.LAB_CATALOG_VIEW,
    PERMISSIONS.LAB_CATALOG_MANAGE,
    PERMISSIONS.LAB_CATALOG_ARCHIVE,
    PERMISSIONS.LAB_CATALOG_SPECIMEN_MANAGE,
    PERMISSIONS.LAB_CATALOG_RANGE_MANAGE,
    PERMISSIONS.LAB_CATALOG_CRITICAL_MANAGE,
    PERMISSIONS.LAB_CATALOG_PANEL_MANAGE,
    PERMISSIONS.LAB_CATALOG_SERVICE_MAP,
    PERMISSIONS.LAB_CATALOG_NHIS_MANAGE,
    PERMISSIONS.LAB_CATALOG_IMPORT,
    PERMISSIONS.LAB_CATALOG_BULK_UPDATE,
    PERMISSIONS.HISTOPATHOLOGY_VIEW, PERMISSIONS.HISTOPATHOLOGY_MANAGE,
    PERMISSIONS.BLOODBANK_VIEW, PERMISSIONS.BLOODBANK_MANAGE,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  radiographer: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW,
    PERMISSIONS.IMAGING_VIEW, PERMISSIONS.IMAGING_PERFORM, PERMISSIONS.IMAGING_REPORT,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW,
  ],

  receptionist: [
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_EDIT,
    PERMISSIONS.ENCOUNTER_VIEW, PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.APPOINTMENT_VIEW, PERMISSIONS.APPOINTMENT_CREATE, PERMISSIONS.APPOINTMENT_RESCHEDULE, PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.TRIAGE_VIEW,
    PERMISSIONS.BED_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  cashier: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_CANCEL,
    PERMISSIONS.INSURANCE_VIEW,
    // NHIA CLAIM-it — view generation history + download XML
    PERMISSIONS.NHIA_CLAIM_VIEW,
    // Upstream NHIS workflow — cashier can view coverage/attendance/readiness (read-only)
    PERMISSIONS.ENCOUNTER_COVERAGE_VIEW,
    PERMISSIONS.ATTENDANCE_VERIFICATION_VIEW,
    PERMISSIONS.CLAIM_READINESS_VIEW,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  accountant: [
    PERMISSIONS.PATIENT_VIEW,
    PERMISSIONS.BILLING_VIEW, PERMISSIONS.BILLING_CREATE, PERMISSIONS.BILLING_DISCOUNT, PERMISSIONS.BILLING_REFUND, PERMISSIONS.BILLING_PAYMENT, PERMISSIONS.BILLING_CANCEL,
    PERMISSIONS.INSURANCE_VIEW, PERMISSIONS.INSURANCE_CLAIM,
    PERMISSIONS.INSURANCE_PROVIDER_VIEW, PERMISSIONS.INSURANCE_PROVIDER_MANAGE,
    PERMISSIONS.INSURANCE_PLAN_MANAGE, PERMISSIONS.INSURANCE_COVERAGE_MANAGE,
    PERMISSIONS.INSURANCE_ELIGIBILITY_MANAGE, PERMISSIONS.INSURANCE_AUTHORIZATION_MANAGE,
    // NHIA CLAIM-it XML integration (generate + view, no config)
    PERMISSIONS.NHIA_CLAIM_VIEW, PERMISSIONS.NHIA_CLAIM_GENERATE,
    // Upstream NHIS workflow — accountant can view coverage, view attendance, evaluate readiness
    PERMISSIONS.ENCOUNTER_COVERAGE_VIEW,
    PERMISSIONS.ATTENDANCE_VERIFICATION_VIEW,
    PERMISSIONS.CLAIM_READINESS_VIEW, PERMISSIONS.CLAIM_READINESS_EVALUATE,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT, PERMISSIONS.ANALYTICS_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
    // Finance permissions
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_MANAGE,
    PERMISSIONS.FINANCE_REPORT_VIEW, PERMISSIONS.FINANCE_REPORT_EXPORT,
    // Payroll permissions (read-only for accounting review)
    PERMISSIONS.PAYROLL_VIEW, PERMISSIONS.PAYROLL_REVIEW,
    PERMISSIONS.PAYSLIP_VIEW,
  ],

  records_officer: [
    PERMISSIONS.PATIENT_VIEW, PERMISSIONS.PATIENT_CREATE, PERMISSIONS.PATIENT_EDIT, PERMISSIONS.PATIENT_MERGE, PERMISSIONS.PATIENT_EXPORT,
    PERMISSIONS.CLINICAL_VIEW,
    PERMISSIONS.ENCOUNTER_VIEW, PERMISSIONS.ENCOUNTER_CREATE,
    PERMISSIONS.ADMISSION_VIEW, PERMISSIONS.BED_VIEW,
    PERMISSIONS.BILLING_VIEW,
    PERMISSIONS.INSURANCE_VIEW,
    // NHIA CLAIM-it — records officers can view + generate claim XML
    PERMISSIONS.NHIA_CLAIM_VIEW, PERMISSIONS.NHIA_CLAIM_GENERATE,
    // Upstream NHIS workflow — records officers are the PRIMARY users (capture coverage, attendance, evaluate readiness)
    PERMISSIONS.ENCOUNTER_COVERAGE_VIEW, PERMISSIONS.ENCOUNTER_COVERAGE_MANAGE,
    PERMISSIONS.ATTENDANCE_VERIFICATION_VIEW, PERMISSIONS.ATTENDANCE_VERIFICATION_CAPTURE, PERMISSIONS.ATTENDANCE_VERIFICATION_VERIFY,
    PERMISSIONS.CLAIM_READINESS_VIEW, PERMISSIONS.CLAIM_READINESS_EVALUATE,
    PERMISSIONS.DOCUMENT_UPLOAD, PERMISSIONS.DOCUMENT_VIEW, PERMISSIONS.DOCUMENT_DELETE,
    PERMISSIONS.REPORT_VIEW, PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],

  inventory_officer: [
    PERMISSIONS.INVENTORY_VIEW, PERMISSIONS.INVENTORY_RECEIVE, PERMISSIONS.INVENTORY_ISSUE, PERMISSIONS.INVENTORY_ADJUST, PERMISSIONS.INVENTORY_TRANSFER,
    PERMISSIONS.IMMUNIZATION_VIEW, PERMISSIONS.IMMUNIZATION_MANAGE,
    PERMISSIONS.PROCUREMENT_MANAGE,
    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.TASK_ASSIGN, PERMISSIONS.TASK_COMPLETE,
  ],
};

// Module catalog used by the UI to filter the sidebar by role
export const ROLE_LABELS: Record<string, string> = {
  super_admin: "Super Administrator",
  organization_admin: "Organization Administrator",
  facility_admin: "Facility Administrator",
  doctor: "Doctor / Medical Officer",
  nurse: "Nurse",
  pharmacist: "Pharmacist",
  laboratory_scientist: "Laboratory Scientist",
  radiographer: "Radiographer",
  receptionist: "Receptionist",
  cashier: "Cashier",
  accountant: "Accountant",
  records_officer: "Records Officer",
  inventory_officer: "Inventory Officer",
};
